update build scripts

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,25 +7,75 @@ on:
       - master # Only check feature branches
 
 jobs:
-  build:
-    runs-on: ubuntu-18.04
+  linux:
+    name: Linux (.NET 6)
+    runs-on: ubuntu-20.04
 
     steps:
-      - uses: actions/checkout@v2
+      - name: Clone Repository
+        uses: actions/checkout@v2
 
-      - name: Branch name
-        id: branch_name
+      - name: Install .NET 6
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: '6.0.x'
+
+      - name: Prepare Environment
         run: |
-          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
-          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
-          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
+          . mod.config;
+          awk '/\r$$/ { exit(1); }' mod.config || (printf "Invalid mod.config format. File must be saved using unix-style (LF, not CRLF or CR) line endings.\n"; exit 1);
+      - name: Check Code
+        run: |
+          make check
+          make check-packaging-scripts
+      - name: Check Mod
+        run: |
+          sudo apt-get install lua5.1
+          make check-scripts
+          make test
+  linux-mono:
+    name: Linux (mono)
+    runs-on: ubuntu-20.04
 
-      - uses: satackey/action-docker-layer-caching@v0.0.11
-        # Ignore the failure of a step and avoid terminating the job.
-        continue-on-error: true
+    steps:
+      - name: Clone Repository
+        uses: actions/checkout@v2
 
-      - name: Build docker
-        run: docker build -t openra-build .
+      - name: Prepare Environment
+        run: |
+          . mod.config;
+          awk '/\r$$/ { exit(1); }' mod.config || (printf "Invalid mod.config format. File must be saved using unix-style (LF, not CRLF or CR) line endings.\n"; exit 1);
+      - name: Check Code
+        run: |
+          # check-packaging-scripts does not depend on .net/mono, so is not needed here
+          mono --version
+          make RUNTIME=mono check
+      - name: Check Mod
+        run: |
+          # check-scripts does not depend on .net/mono, so is not needed here
+          make RUNTIME=mono test
+  windows:
+    name: Windows (.NET 6.0)
+    runs-on: windows-2019
 
-      - name: Build CA
-        run: docker run -e RELEASE_VERSION=${GITHUB_SHA} -v $GITHUB_WORKSPACE:/workdir --rm openra-build ./build-docker.sh
+    steps:
+      - name: Clone Repository
+        uses: actions/checkout@v2
+
+      - name: Install .NET 6
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: '6.0.x'
+
+      - name: Check Code
+        shell: powershell
+        run: |
+          # Work around runtime failures on the GH Actions runner
+          dotnet nuget locals all --clear
+          .\make.ps1 check
+      - name: Check Mods
+        run: |
+          chocolatey install lua --version 5.1.5.52
+          $ENV:Path = $ENV:Path + ";C:\Program Files (x86)\Lua\5.1\"
+          .\make.ps1 check-scripts
+          .\make.ps1 test
